# Generated by Django 5.2 on 2025-04-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sathi', '0004_alter_note_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
